name: Apishot
# Run workflow whenever a pull_request has been closed to the `master` and `branch-*` branches
on:
  workflow_dispatch:
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: |
          echo "SONATYPE_USERNAME=${{ secrets.SONATYPE_USERNAME }}" >>  $GITHUB_ENV
          echo "SONATYPE_PASSWORD=${{ secrets.SONATYPE_PASSWORD }}" >>  $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >>  $GITHUB_ENV
      - uses: smartsquaregmbh/delete-old-packages@v0.3.1
        with:
          version-pattern: "^\\d+\\.\\d+\\.\\d+-SNAPSHOT$" # Remove all previous SNAPSHOT versions
          keep: 0
          names: |
            ai.starlake.starlake-core_2.13
      - uses: actions/checkout@v4
      - name: Set up Zulu 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Trigger starlake-api workflow
        if: ${{ success() }}
        id: trigger-starlake-api
        env:
          GITHUB_TOKEN: ${{ secrets.STARLAKE_API_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/starlake-ai/starlake-api/actions/workflows/docker-hub.yml/dispatches \
          -d '{"ref":"main"}'
      - name: trigger-starlake-api
        if: github.event.workflow_run.conclusion == 'success' # Run only when workflow run has succeeded, i.e. all jobs have succeeded
        runs-on: ubuntu-latest
        steps:
          - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.STARLAKE_API_TOKEN }} # Fine-grained GitHub PAT that was saved as repository secret
          script: |
            await github.rest.actions.createworkflowDispatch({
            owner: 'starlake-ai',
            repo: 'starlake-api',
            workflow_id: 'docker-hub.yml',
            ref: 'main'
          })